name: npm-master

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - uses: codecov/codecov-action@v1.0.2
        with:
          node-version: 12
          token: ${{secrets.CODECOV_TOKEN}}
      - run: npm ci
      - run: npm test
          
  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
